name: Docker

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  docker:
    name: Build image and push to GHRC
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ghcr.io
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v') }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.tag }}
