name: List affected rockspecs

on:
  workflow_call:
    outputs:
      rockspecs:
        value: ${{ jobs.affected.outputs.rockspecs }}

jobs:
  affected:
    name: Find edited rockspecs
    runs-on: ubuntu-24.04
    outputs:
      rockspecs: >-
        ${{
          steps.changed-files.outputs.all_modified_files &&
          format('["{0}"]', steps.changed-files.outputs.all_modified_files) ||
          null
        }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - id: changed-files
        # !!WARNING!! This upstream repository was compromised and **all tags**
        # have been pointed to a recent compromized commit. This pinned hash is
        # to get an actually old uncompromized version for now as an emergency
        # stop gap. Eventually we should move to an uncompromised action source.
        # c.f. https://github.com/tj-actions/changed-files/issues/2463
        # c.f. https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
        uses: tj-actions/changed-files@934b2d2c7e653bb8c968afed5a0428617f09aa24
        with:
          since_last_remote_commit: true
          files: |
            *.rockspec
            rockspecs/*.rockspec
          separator: '", "'
